version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 30
  - package-ecosystem: "bundler"
    directory: "/site"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 30